### ISSUE TITLE
how can i training it again?

### ISSUE THREAD

**Issue by sanren99999** [VPanjeta/hotdog-or-not-hotdog#1]
Hi,VPanjeta!
you said that:"Retraining done by replacing last layer of Inception model.",but i want to training it and i don't known how to do it.

In fact,i want to recognize another data which like image data, so, could you offer me the training source code by cnn, thanks!

**Comment by VPanjeta** [comment]
Hey.
The retrain script I used is provided by tensorflow which has now moved to tensorflow hub. You can get it [here](https://github.com/tensorflow/hub/tree/master/examples/image_retraining)

You can check the flags as to how to retrain it. There is a very detailed 5 minute video by Siraj Raval on how to collect data and use this script to generate weight. Link to the video: [How to build an image classifier in 5 minutes](https://www.youtube.com/watch?v=QfNvhPx5Px8) .
Hope this helps.
